### ISSUE TITLE
Dependency missing error

### ISSUE THREAD

**Issue by frankjmlinar** [priscian/climeseries#1]
I am getting the following error when I try to install climeseries
I am using the following command install_github("priscian/climeseries") inside R
The first time I tried the install, I saw a lot of files being loaded. Subsequent install attempts show none.

ERROR: dependency ‘rhdf5’ is not available for package ‘climeseries’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/climeseries’
Installation failed: Command failed (1)

I tried a couple different mirrors, too.

stuff displayed between the install command and the error

Downloading GitHub repo priscian/climeseries@master
from URL https://api.github.com/repos/priscian/climeseries/zipball/master
Installing climeseries
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/pf/0d5gzdpn5rg0dzlw1fcwpyjm0000gn/T/Rtmpr6F1wW/devtools48a731f8cd00/priscian-climeseries-550ec33'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library'  \
  --install-tests

**Comment by priscian** [comment]
Sorry about the error—I might need to pay more attention to that dependency.

Try the installation procedure for "rhdf5" [here](https://bioconductor.org/packages/release/bioc/html/rhdf5.html). I'm hoping "climeseries" will then install okay for you after that using 'install_github()'. If that procedure doesn't work, let me know.

**Comment by frankjmlinar** [comment]
It looks like it installed. I'll whine some more if I run into additional problems.
Thanks
Frank
