### ISSUE TITLE
Install fails on MacOS Catalina

### ISSUE THREAD

**Issue by nidan841g** [priscian/climeseries#2]
I have tried installing with the script from the README.md, and with devtools and `install_github("priscian/climeseries")`, both fail thusly with this error msg visible in the R console:
```
> install_github("priscian/climeseries")
Downloading GitHub repo priscian/climeseries@HEAD
Skipping 1 packages not available: rhdf5
✔  checking for file ‘/private/var/folders/5d/gv8ewzpn3jjb8mdgrp7j4x2h0000gr/T/Rtmp7Is1S5/remotes877dc189d14/priscian-climeseries-6353344/DESCRIPTION’ (875ms)
─  preparing ‘climeseries’: (3.9s)
─  building ‘climeseries_0.129.0.tar.gz’ ...paring ‘climeseries’: (3.9s)
... <many lines deleted here>
Installing package into ‘/Users/<redacted>/Library/R/x86_64/4.2/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘climeseries’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(x) : there is no package called ‘mgsub’
Error: unable to load R code in package ‘climeseries’
Execution halted
ERROR: lazy loading failed for package ‘climeseries’
* removing ‘/Users/john/Library/R/x86_64/4.2/library/climeseries’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/5d/gv9ywzpn4jjb8mdgrp8k4x2h0000gr/T//Rtmp7Is1S5/file877d23f09240/climeseries_0.129.0.tar.gz’ had non-zero exit status
  ```

**Comment by priscian** [comment]
It should work if you install "mgsub" first—but I'll check. Frankly, the package is a bit of a mess, because I didn't know what I wanted to do with it when I started; now that I do know, I'm redoing the whole thing from scratch, but it's not ready yet. Let me clean up the dependencies a little bit (maybe we don't actually need mgsub) and try a fresh install, and I'll alert you when it's ready.

**Comment by nidan841g** [comment]
Thanks. This was a fresh install of R 4.2.1 btw.

**Comment by nidan841g** [comment]
> It should work if you install "mgsub" first—but I'll check.

I loaded mgsub before running `remotes::install_github("priscian/climeseries")` and it errored out the same way.

**Comment by nidan841g** [comment]
I have been able to install successfully by first installing `rhdf5`, `mgsub`, and `purrr` in the R console, extracting the files from the downloaded tar archive,  and then installing `climeseries` in a shell session with `R CMD build climeseries` and `R CMD install climeseries`.
